# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='imgurl',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
